[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.16.0"
  NPM_VERSION = "10.2.4"
  PYTHON_VERSION = ""
  RUBY_VERSION = ""
  GO_VERSION = ""
  PHP_VERSION = "" 