[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = ""
  RUBY_VERSION = ""
  GO_VERSION = ""
  PHP_VERSION = ""

# Cache configuration
[[plugins]]
  package = "@netlify/plugin-cache-core"

[[plugins]]
  package = "@netlify/plugin-cache-npm"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 